# yaml-language-server: $schema=../../../schema/local.json
binds:
- port: 8080
  listeners:
  - protocol: HTTP
    routes:
    # MCP protocol endpoint
    - name: "mcp-route"
      matches:
      - path:
          pathPrefix: /mcp
      backends:
      - host: test-server:3001
    # A2A protocol endpoint  
    - name: "a2a-route"
      matches:
      - path:
          pathPrefix: /a2a
      backends:
      - host: test-server:3001
    # HTTP benchmark endpoint (catch-all for /test and other paths)
    - name: "benchmark-route"
      matches:
      - path:
          pathPrefix: /
      backends:
      - host: test-server:3001
