config:
  admin_addr: "127.0.0.1:15000"
  stats_addr: "0.0.0.0:15020"
  readiness_addr: "0.0.0.0:15021"
  enable_ipv6: false
  network: "benchmark"
  
  # MCP proxy configuration for benchmarking
  listeners:
    - name: "mcp-benchmark"
      address: "0.0.0.0:8080"
      protocol: "mcp"
      
  routes:
    - name: "mcp-benchmark-route"
      match:
        protocol: "mcp"
      backend: "mcp-benchmark-backend"
      
  backends:
    - name: "mcp-benchmark-backend"
      address: "127.0.0.1:3002"
      protocol: "mcp"
      health_check:
        enabled: false  # Disable for benchmarking
        
  # MCP-specific optimizations
  mcp:
    max_message_size: 10485760    # 10MB
    connection_timeout: "30s"
    read_timeout: "60s"
    write_timeout: "60s"
    
  # Optimize for performance testing
  http2:
    window_size: 8388608          # 8MB for larger MCP messages
    connection_window_size: 33554432  # 32MB
    frame_size: 2097152           # 2MB
    pool_max_streams_per_conn: 50  # Fewer streams for MCP
    pool_unused_release_timeout: "600s"
    
  # Disable logging for accurate performance measurement
  logging:
    filter: "level >= 'error'"
    
  # Disable tracing for benchmarking
  tracing:
    endpoint: null
