name: E2E Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            ui/package-lock.json
          
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
            
      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
            
      - name: Install dependencies
        run: |
          npm ci
          cd ui
          npm ci

      - name: Build AgentGateway
        run: |
          cargo build --release --bin agentgateway

      - name: Run E2E Tests
        run: |
          # Run E2E tests using the comprehensive test runner
          echo "🚀 Running E2E tests in CI environment"
          
          # Use the minimal test approach for CI to ensure reliability
          echo "📋 Running minimal E2E test suite for CI validation..."
          node scripts/test-e2e-minimal.js --verbose
          
          # If minimal tests pass, run a focused smoke test suite
          if [ $? -eq 0 ]; then
            echo "✅ Minimal tests passed, running smoke test suite..."
            
            # Use the comprehensive test runner with conservative settings for CI
            chmod +x scripts/run-e2e-tests.sh
            ./scripts/run-e2e-tests.sh \
              --mode sequential \
              --workers 1 \
              --timeout 120 \
              --no-auto-detect \
              --verbose
          else
            echo "❌ Minimal tests failed, skipping full test suite"
            exit 1
          fi
        env:
          CI: true
          SKIP_BUILD: false
          AGENTGATEWAY_BINARY: ./target/release/agentgateway

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-results-node-${{ matrix.node-version }}
          path: |
            ui/cypress/videos/
            ui/cypress/screenshots/
            ui/cypress/results/
          retention-days: 7
          if-no-files-found: ignore
          
      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-reports-node-${{ matrix.node-version }}
          path: ui/cypress/reports/
          retention-days: 7
          if-no-files-found: ignore

      - name: Upload minimal test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: minimal-test-report-node-${{ matrix.node-version }}
          path: |
            minimal-test-report.json
            smart-defaults.json
            .e2e-setup-config
          retention-days: 7
          if-no-files-found: ignore

      - name: Upload test configuration
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-config-node-${{ matrix.node-version }}
          path: |
            test-config*.yaml
          retention-days: 3
          if-no-files-found: ignore

  e2e-tests-summary:
    runs-on: ubuntu-latest
    needs: e2e-tests
    if: always()

    steps:
      - name: Check E2E test results
        run: |
          if [[ "${{ needs.e2e-tests.result }}" == "success" ]]; then
            echo "✅ All E2E tests passed successfully!"
          else
            echo "❌ E2E tests failed"
            exit 1
          fi
